fn_single_line = false
hard_tabs = false
imports_granularity = "Module"
indent_style = "Block"
match_block_trailing_comma = true
reorder_impl_items = true
style_edition = "2024"
use_small_heuristics = "Max"
wrap_comments = true
group_imports = "StdExternalCrate"
