fn_single_line = false
hard_tabs = false
imports_granularity = "crate"
indent_style = "Block"
match_block_trailing_comma = true
reorder_impl_items = true
version = "Two"
use_small_heuristics = "Max"
wrap_comments = true
group_imports = "StdExternalCrate"
